### ISSUE TITLE
feature/picture-uploads-for-products

### ISSUE THREAD

**Issue by KooshaG** [SOEN-341-Project/Group-P-soen341project2022#38]
## User Story: (5 points)
As a seller, I want to upload a picture when I'm listing my item.

## Brief Description
Make a function that can take a picture and uploads it to google cloud storage
## Feature Requirements

- [x]  Google cloud storage
- [x]  Make the picture public
- [x]  Have the upload possible from the client

## Sub-tasks (sub-issues)
 - #28 

# Additional context
