### ISSUE TITLE
feature/product-view-more-page

### ISSUE THREAD

**Issue by aspyridakos** [SOEN-341-Project/Group-P-soen341project2022#48]
## User Story: (4 points)
As a user I want to be able to access a more detailed product page when clicking on each product box in the product grid because I want to view more of the product info and be able to add the product to my cart.

## Brief Description
Full page product view which includes additional and more detailed product info than the product grid boxes. This page should include an option to add to cart, select quantities, and view product descriptions.

## Feature Requirements
- [x] Back button to navigate back to product grid
- [x] Add to cart button
- [x] Price, description (consider adding a expandable dropdown for this), brand, seller info, etc. (display all available product details)
- [x] Quantity buttons (+/-)
- [x] Product image taking up most of the page
- [ ] View cart link and added product info in alert once "add to cart" has been clicked (_optional_)
