### ISSUE TITLE
feature/admin-page

### ISSUE THREAD

**Issue by Adamo-O** [SOEN-341-Project/Group-P-soen341project2022#88]
## User Story: (4 points)
As an admin I should be able to view all products and users in a dedicated page.

## Brief Description
Creating admin page with tables for managing products and managing accounts in the database.

## Feature Requirements
- Add products table
   - Products should be editable
- Add accounts table
   - Can edit user and seller accounts
- Add orders table
   - Can view orders

## Risks
- Admin page must be clear and concise that satisfies the client's requirements. Admin page can become not user-friendly if too much information is provided.

## Acceptance Tests
- [x] On Admin page, a table of products and a table of managing accounts appear.
- [x] Products on table of products should be deletable.
- [x] Products on table of products should be modifiable.
- [x] Seller accounts on table of accounts must be deletable.
- [x] Customer accounts on table of accounts must be deletable.
